#!/usr/bin/env python3
"""
world_to_occupancy_map.py

Converts one of this package's own orchard world SDF files (worlds/
orchard_map_{a,b,c}.sdf) into a standard ROS map_server map.pgm/map.yaml
pair -- the SAME format problog_project's own load_map_yaml reads (see
amiga_ros2_planners/scripts/export_orchard_map.py, whose write_map()
this mirrors byte-for-byte: same PIXEL_FREE/OCCUPIED/UNKNOWN values,
same negate/occupied_thresh/free_thresh, same row-flip convention).

Unlike export_orchard_map.py (which reads tree positions out of a
checked-in mission fixture and treats every obstacle as a circle), this
script reads geometry directly out of the world SDF and the model.sdf
files it <include>s, since these worlds are ours -- generated by
generate_orchard_world.py plus the fence/house placement we added by
hand -- so the exact geometry is already known and doesn't need mesh
slicing:
  - trees: circles, using the SAME trunk_collision cylinder radius
    baked into generate_orchard_world.py's TREE_TEMPLATE (1.2m), read
    straight out of each tree <model>'s own <collision> so this stays
    correct if that template ever changes.
  - fence panels: oriented rectangles, sized from models/fence/model.sdf's
    own <box><size>, positioned/oriented from each <include>'s <pose>.
  - the house (orchard_map_a only): ONE oriented rectangle covering its
    full mesh bounding box (scaled by model.sdf's <scale>, unit-converted
    from house_1.dae's own <asset><unit>), positioned/oriented from its
    <include>'s <pose>. Per request, the house is filled solid -- no
    interior walls/rooms are modeled, matching "no free space inside".

Occupancy semantics match build_grid_map's own inflate-by-robot-radius
convention (planning_core.py): a cell is occupied if it lies within
`inflate` metres of any obstacle's own boundary (a tree's canopy edge,
a fence panel's face, the house's outer wall) -- not just literally
inside/on it. inflate defaults to PLANNING_INFLATE_M (0.3), the same
default build_grid_map itself uses and that export_orchard_map.py
implicitly relies on by not overriding it.

Usage:
    python3 world_to_occupancy_map.py \
        --world ../worlds/orchard_map_a.sdf \
        --out ../maps --map-name orchard_map_a
"""
import argparse
import math
import os
import xml.etree.ElementTree as ET

import numpy as np
import yaml
from PIL import Image

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_PACKAGE_DIR = os.path.dirname(_THIS_DIR)

# Same convention as export_orchard_map.py / problog_project's own
# load_map_yaml: negate=0 means LOW pixel value ("dark") = occupied.
PIXEL_FREE = 254
PIXEL_OCCUPIED = 0

# Same defaults planning_core.py's build_grid_map itself uses.
DEFAULT_RESOLUTION = 0.1
DEFAULT_MARGIN = 5.0
DEFAULT_INFLATE = 0.3

COLLADA_NS = "{http://www.collada.org/2005/11/COLLADASchema}"


def _pose_xyyaw(pose_text):
    """'<pose>x y z roll pitch yaw</pose>' text -> (x, y, yaw)."""
    x, y, _z, _roll, _pitch, yaw = (float(v) for v in pose_text.split())
    return x, y, yaw


def parse_tree_circles(world_root):
    """[(x, y, radius), ...] -- one per <model name="tree_..">, radius
    read from that tree's own trunk_collision cylinder (not hardcoded,
    so this stays correct if generate_orchard_world.py's own template
    ever changes)."""
    circles = []
    for model in world_root.iter("model"):
        name = model.get("name", "")
        if not name.startswith("tree_"):
            continue
        pose = model.find("pose")
        radius_el = model.find(".//collision[@name='trunk_collision']/geometry/cylinder/radius")
        if pose is None or radius_el is None:
            continue
        x, y, _yaw = _pose_xyyaw(pose.text)
        circles.append((x, y, float(radius_el.text)))
    return circles


def get_fence_footprint(models_dir):
    """(length, thickness) metres, read from models/fence/model.sdf's own
    <box><size>. Its own <link> pose is a pure Z offset (rests it on the
    ground) so it doesn't affect the XY footprint."""
    tree = ET.parse(os.path.join(models_dir, "fence", "model.sdf"))
    size_text = tree.find(".//visual/geometry/box/size").text
    thickness, length, _height = (float(v) for v in size_text.split())
    return length, thickness


def parse_fence_rects(world_root, length, thickness):
    """[(cx, cy, yaw, length, thickness), ...] -- one per <include> of
    model://fence."""
    rects = []
    for include in world_root.iter("include"):
        uri = include.find("uri")
        pose = include.find("pose")
        if uri is None or pose is None or uri.text != "model://fence":
            continue
        x, y, yaw = _pose_xyyaw(pose.text)
        rects.append((x, y, yaw, length, thickness))
    return rects


def get_house_local_bbox(models_dir):
    """(size_x, size_y) metres -- house_1's full mesh bounding box XY
    extent, in its own model.sdf's <scale>, unit-converted from
    house_1.dae's own <asset><unit>. Same computation used to place the
    house in orchard_map_a in the first place."""
    model_sdf = ET.parse(os.path.join(models_dir, "house_1", "model.sdf"))
    scale_text = model_sdf.find(".//visual/geometry/mesh/scale").text
    scale_x, scale_y, _scale_z = (float(v) for v in scale_text.split())

    dae_path = os.path.join(models_dir, "house_1", "meshes", "house_1.dae")
    dae_root = ET.parse(dae_path).getroot()
    unit_el = dae_root.find(f"{COLLADA_NS}asset/{COLLADA_NS}unit")
    unit_scale = float(unit_el.get("meter", "1.0")) if unit_el is not None else 1.0

    min_x = min_y = float("inf")
    max_x = max_y = float("-inf")
    for source in dae_root.iter(f"{COLLADA_NS}source"):
        if "position" not in source.get("id", "").lower():
            continue
        float_array = source.find(f"{COLLADA_NS}float_array")
        if float_array is None or not float_array.text:
            continue
        values = [float(v) for v in float_array.text.split()]
        for i in range(0, len(values) - 2, 3):
            x, y = values[i] * unit_scale, values[i + 1] * unit_scale
            min_x, max_x = min(min_x, x), max(max_x, x)
            min_y, max_y = min(min_y, y), max(max_y, y)

    return (max_x - min_x) * scale_x, (max_y - min_y) * scale_y


def parse_house_rect(world_root, size_x, size_y):
    """(cx, cy, yaw, size_x, size_y) or None if this world has no house.
    The house's own mesh origin isn't at its bbox center (see the
    placement math used when it was first added), but for occupancy
    purposes we only need its OVERALL footprint size and pose -- a
    filled rectangle at the include's own pose covers the same ground
    area regardless of where the mesh's internal origin sits, since we
    always want the whole thing solid anyway."""
    for include in world_root.iter("include"):
        uri = include.find("uri")
        pose = include.find("pose")
        if uri is None or pose is None or uri.text != "model://house_1":
            continue
        x, y, yaw = _pose_xyyaw(pose.text)
        return x, y, yaw, size_x, size_y
    return None


def _rect_distance(px, py, cx, cy, yaw, length_x, length_y):
    """Euclidean distance from point (px,py) to the rectangle centered
    at (cx,cy), rotated by yaw, with full side lengths (length_x,
    length_y) along its own local x/y axes. 0 if the point is inside."""
    dx, dy = px - cx, py - cy
    cos_y, sin_y = math.cos(-yaw), math.sin(-yaw)
    local_x = dx * cos_y - dy * sin_y
    local_y = dx * sin_y + dy * cos_y
    half_x, half_y = length_x / 2.0, length_y / 2.0
    ex = max(abs(local_x) - half_x, 0.0)
    ey = max(abs(local_y) - half_y, 0.0)
    return math.hypot(ex, ey)


def build_map(circles, rects, resolution, margin, inflate):
    """Rasterize every circle/rect obstacle into one occupancy grid,
    same shape/semantics as planning_core.py's build_grid_map: a cell is
    occupied if within `inflate` metres of any obstacle's own boundary."""
    xs, ys = [], []
    for x, y, r in circles:
        xs += [x - r - margin, x + r + margin]
        ys += [y - r - margin, y + r + margin]
    for cx, cy, yaw, length_x, length_y in rects:
        half_diag = math.hypot(length_x, length_y) / 2.0
        xs += [cx - half_diag - margin, cx + half_diag + margin]
        ys += [cy - half_diag - margin, cy + half_diag + margin]

    min_x, max_x = min(xs), max(xs)
    min_y, max_y = min(ys), max(ys)
    width = max(1, int(math.ceil((max_x - min_x) / resolution)))
    height = max(1, int(math.ceil((max_y - min_y) / resolution)))

    data = np.zeros((height, width), dtype=np.uint8)
    rows, cols = np.indices(data.shape)
    world_x = min_x + (cols + 0.5) * resolution
    world_y = min_y + (rows + 0.5) * resolution

    for x, y, r in circles:
        occ_r = r + inflate
        data[(world_x - x) ** 2 + (world_y - y) ** 2 <= occ_r ** 2] = 100

    for cx, cy, yaw, length_x, length_y in rects:
        dx, dy = world_x - cx, world_y - cy
        cos_y, sin_y = math.cos(-yaw), math.sin(-yaw)
        local_x = dx * cos_y - dy * sin_y
        local_y = dx * sin_y + dy * cos_y
        half_x, half_y = length_x / 2.0 + inflate, length_y / 2.0 + inflate
        data[(np.abs(local_x) <= half_x) & (np.abs(local_y) <= half_y)] = 100

    return data, resolution, (min_x, min_y)


def write_map(data, resolution, origin, out_dir, map_name):
    """occupancy array -> <out_dir>/<map_name>.pgm + .yaml. Row 0 of
    `data` is min-y (nav_msgs/OccupancyGrid convention); a PGM's row 0
    is the TOP of the image = max-y, so flip once here, same as
    export_orchard_map.py's own write_map."""
    pixels = np.full(data.shape, PIXEL_FREE, dtype=np.uint8)
    pixels[data >= 100] = PIXEL_OCCUPIED
    pixels = np.flipud(pixels)

    os.makedirs(out_dir, exist_ok=True)
    pgm_path = os.path.join(out_dir, f"{map_name}.pgm")
    yaml_path = os.path.join(out_dir, f"{map_name}.yaml")

    Image.fromarray(pixels, mode="L").save(pgm_path)

    meta = {
        "image": f"{map_name}.pgm",
        "resolution": resolution,
        "origin": [origin[0], origin[1], 0.0],
        "negate": 0,
        "occupied_thresh": 0.65,
        "free_thresh": 0.196,
    }
    with open(yaml_path, "w") as f:
        yaml.safe_dump(meta, f, default_flow_style=False)

    return pgm_path, yaml_path


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--world", required=True, help="Path to an orchard_map_*.sdf world file.")
    ap.add_argument("--models-dir", default=os.path.join(_PACKAGE_DIR, "models"),
                     help="Where fence/ and house_1/ live (default: this package's own models/).")
    ap.add_argument("--out", default=os.path.join(_PACKAGE_DIR, "maps"))
    ap.add_argument("--map-name", default=None, help="Defaults to the world file's own basename.")
    ap.add_argument("--resolution", type=float, default=DEFAULT_RESOLUTION,
                     help=f"Metres per cell (default: {DEFAULT_RESOLUTION}, matching "
                     "problog_project's own committed maps and this repo's own "
                     "export_orchard_map.py -- NOT the 0.05 in problog_project's "
                     "unused module/devtools/map_generation.py sample script).")
    ap.add_argument("--margin", type=float, default=DEFAULT_MARGIN,
                     help=f"Blank border beyond the outermost geometry, metres "
                     f"(default: {DEFAULT_MARGIN}, matching export_orchard_map.py).")
    ap.add_argument("--inflate", type=float, default=DEFAULT_INFLATE,
                     help=f"Occupied zone grown this far beyond each obstacle's own "
                     f"boundary, metres (default: {DEFAULT_INFLATE} = "
                     "planning_core.py's own PLANNING_INFLATE_M).")
    args = ap.parse_args()

    map_name = args.map_name or os.path.splitext(os.path.basename(args.world))[0]

    world_root = ET.parse(args.world).getroot()

    circles = parse_tree_circles(world_root)
    print(f"trees: {len(circles)}")

    fence_length, fence_thickness = get_fence_footprint(args.models_dir)
    rects = parse_fence_rects(world_root, fence_length, fence_thickness)
    print(f"fence panels: {len(rects)} ({fence_length}m x {fence_thickness}m each)")

    house_size = get_house_local_bbox(args.models_dir)
    house_rect = parse_house_rect(world_root, *house_size)
    if house_rect is not None:
        rects.append(house_rect)
        print(f"house: {house_size[0]:.2f}m x {house_size[1]:.2f}m footprint, filled solid")

    data, resolution, origin = build_map(circles, rects, args.resolution, args.margin, args.inflate)
    print(f"grid: {data.shape[1]}x{data.shape[0]} cells at {resolution} m/cell, "
          f"origin=({origin[0]:.2f}, {origin[1]:.2f})")

    pgm_path, yaml_path = write_map(data, resolution, origin, args.out, map_name)
    print(f"wrote {pgm_path}")
    print(f"wrote {yaml_path}")


if __name__ == "__main__":
    main()
