#!/usr/bin/env python3
"""
world_to_occupancy_map.py

Converts one of this package's own orchard world SDF files (worlds/
orchard_map_{a,b,c}.sdf) into a standard ROS map_server map.pgm/map.yaml
pair -- the SAME format problog_project's own load_map_yaml reads (see
amiga_ros2_planners/scripts/export_orchard_map.py, whose write_map()
this mirrors byte-for-byte: same PIXEL_FREE/OCCUPIED/UNKNOWN values,
same negate/occupied_thresh/free_thresh, same row-flip convention).

Unlike export_orchard_map.py (which reads tree positions out of a
checked-in mission fixture and treats every obstacle as a circle), this
script reads geometry directly out of the world SDF and the model.sdf
files it <include>s, since these worlds are ours -- generated by
generate_orchard_world.py plus the fence/house placement we added by
hand -- so the exact geometry is already known and doesn't need mesh
slicing:
Every shape below is sized from each model's own <collision> geometry,
never <visual> -- Gazebo's own physics engine only ever collides
against <collision>, so that's the geometry that actually determines
where the robot can/can't go, and it can differ from the visual mesh
(a tree's trunk_collision cylinder, radius 1.2m, is smaller than its
own ~1.85m visual canopy -- canopies visually overlap with no physics
response; only the trunk-scale zone actually blocks the robot):
  - trees: circles, using the trunk_collision cylinder radius baked
    into generate_orchard_world.py's TREE_TEMPLATE (1.2m), read
    straight out of each tree <model>'s own <collision> so this stays
    correct if that template ever changes.
  - fence panels: oriented rectangles, sized from models/fence/model.sdf's
    own <collision><box><size>, positioned/oriented from each
    <include>'s <pose>.
  - the house (orchard_map_a only): ONE oriented rectangle covering its
    full collision mesh bounding box (scaled by model.sdf's own
    <collision><scale>, unit-converted from house_1.dae's own
    <asset><unit> -- the same mesh file both collision and visual
    reference), positioned/oriented from its <include>'s <pose>. Per
    request, the house is filled solid -- no interior walls/rooms are
    modeled, matching "no free space inside".

Occupancy semantics match build_grid_map's own inflate-by-robot-radius
convention (planning_core.py): a cell is occupied if it lies within
`inflate` metres of any obstacle's own boundary (a tree's canopy edge,
a fence panel's face, the house's outer wall) -- not just literally
inside/on it. inflate defaults to PLANNING_INFLATE_M (0.3), the same
default build_grid_map itself uses and that export_orchard_map.py
implicitly relies on by not overriding it.

Also renders a second image per map, "<map_name>_dimensions.png": the
same obstacle layout drawn as a dimensioned technical diagram rather
than an occupancy grid -- the world (map) reference frame's origin and
axes, a metre grid/tick labels, and every obstacle's own shape,
size, and (x,y) position relative to that origin. Meant for visually
auditing the generated map/geometry (are trees where you think they
are, is the fence the right size), not for anything map_server loads.

Usage:
    python3 world_to_occupancy_map.py \
        --world ../worlds/orchard_map_a.sdf \
        --out ../maps --map-name orchard_map_a
"""
import argparse
import math
import os
import xml.etree.ElementTree as ET

import numpy as np
import yaml
from PIL import Image, ImageDraw, ImageFont

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_PACKAGE_DIR = os.path.dirname(_THIS_DIR)

# Same convention as export_orchard_map.py / problog_project's own
# load_map_yaml: negate=0 means LOW pixel value ("dark") = occupied.
PIXEL_FREE = 254
PIXEL_OCCUPIED = 0

# Same defaults planning_core.py's build_grid_map itself uses.
DEFAULT_RESOLUTION = 0.1
DEFAULT_MARGIN = 5.0
DEFAULT_INFLATE = 0.3

COLLADA_NS = "{http://www.collada.org/2005/11/COLLADASchema}"


def _pose_xyyaw(pose_text):
    """'<pose>x y z roll pitch yaw</pose>' text -> (x, y, yaw)."""
    x, y, _z, _roll, _pitch, yaw = (float(v) for v in pose_text.split())
    return x, y, yaw


def parse_tree_circles(world_root):
    """[(x, y, radius, name), ...] -- one per <model name="tree_..">,
    radius read from that tree's own trunk_collision cylinder (not
    hardcoded, so this stays correct if generate_orchard_world.py's own
    template ever changes)."""
    circles = []
    for model in world_root.iter("model"):
        name = model.get("name", "")
        if not name.startswith("tree_"):
            continue
        pose = model.find("pose")
        radius_el = model.find(".//collision[@name='trunk_collision']/geometry/cylinder/radius")
        if pose is None or radius_el is None:
            continue
        x, y, _yaw = _pose_xyyaw(pose.text)
        circles.append((x, y, float(radius_el.text), name))
    return circles


def get_fence_footprint(models_dir):
    """(length, thickness) metres, read from models/fence/model.sdf's own
    <collision><box><size> -- the shape Gazebo's own physics actually
    collides against, not the <visual> (identical values today, but
    this is the one that stays correct if a future fence mesh's visual
    ever diverges from its own collision box). Its own <link> pose is a
    pure Z offset (rests it on the ground) so it doesn't affect the XY
    footprint."""
    tree = ET.parse(os.path.join(models_dir, "fence", "model.sdf"))
    size_text = tree.find(".//collision/geometry/box/size").text
    thickness, length, _height = (float(v) for v in size_text.split())
    return length, thickness


def parse_fence_rects(world_root, length, thickness):
    """[(cx, cy, yaw, size_x, size_y, name), ...] -- one per <include> of
    model://fence. build_map treats (size_x, size_y) as the rectangle's
    own LOCAL x/y extents, and the fence's box in models/fence/model.sdf
    is <size>0.1 5 1.83</size> = (thickness along local x, length along
    local y) -- so size_x=thickness, size_y=length here, NOT (length,
    thickness): swapping these put every panel's long axis on the wrong
    side of the yaw rotation, rendering every fence 90 degrees off from
    its real orientation. `name` is each <include>'s own <name> (e.g.
    "hfence_e_03") -- just for the dimensioned-diagram labels."""
    rects = []
    for include in world_root.iter("include"):
        uri = include.find("uri")
        pose = include.find("pose")
        if uri is None or pose is None or uri.text != "model://fence":
            continue
        x, y, yaw = _pose_xyyaw(pose.text)
        name_el = include.find("name")
        name = name_el.text if name_el is not None else "fence"
        rects.append((x, y, yaw, thickness, length, name))
    return rects


def get_house_local_bbox(models_dir):
    """(size_x, size_y) metres -- house_1's full mesh bounding box XY
    extent, in its own model.sdf's <collision><scale> (the shape
    Gazebo's own physics actually collides against -- identical to the
    <visual> scale today, but this is the one that stays correct if a
    future model ever gives its collision and visual meshes different
    scales), unit-converted from house_1.dae's own <asset><unit> (the
    SAME mesh file collision and visual both reference here). Same
    computation used to place the house in orchard_map_a in the first
    place."""
    model_sdf = ET.parse(os.path.join(models_dir, "house_1", "model.sdf"))
    scale_text = model_sdf.find(".//collision/geometry/mesh/scale").text
    scale_x, scale_y, _scale_z = (float(v) for v in scale_text.split())

    dae_path = os.path.join(models_dir, "house_1", "meshes", "house_1.dae")
    dae_root = ET.parse(dae_path).getroot()
    unit_el = dae_root.find(f"{COLLADA_NS}asset/{COLLADA_NS}unit")
    unit_scale = float(unit_el.get("meter", "1.0")) if unit_el is not None else 1.0

    min_x = min_y = float("inf")
    max_x = max_y = float("-inf")
    for source in dae_root.iter(f"{COLLADA_NS}source"):
        if "position" not in source.get("id", "").lower():
            continue
        float_array = source.find(f"{COLLADA_NS}float_array")
        if float_array is None or not float_array.text:
            continue
        values = [float(v) for v in float_array.text.split()]
        for i in range(0, len(values) - 2, 3):
            x, y = values[i] * unit_scale, values[i + 1] * unit_scale
            min_x, max_x = min(min_x, x), max(max_x, x)
            min_y, max_y = min(min_y, y), max(max_y, y)

    return (max_x - min_x) * scale_x, (max_y - min_y) * scale_y


def parse_house_rect(world_root, size_x, size_y):
    """(cx, cy, yaw, size_x, size_y, name) or None if this world has no
    house. The house's own mesh origin isn't at its bbox center (see
    the placement math used when it was first added), but for occupancy
    purposes we only need its OVERALL footprint size and pose -- a
    filled rectangle at the include's own pose covers the same ground
    area regardless of where the mesh's internal origin sits, since we
    always want the whole thing solid anyway."""
    for include in world_root.iter("include"):
        uri = include.find("uri")
        pose = include.find("pose")
        if uri is None or pose is None or uri.text != "model://house_1":
            continue
        x, y, yaw = _pose_xyyaw(pose.text)
        name_el = include.find("name")
        name = name_el.text if name_el is not None else "house_1"
        return x, y, yaw, size_x, size_y, name
    return None


def compute_bounds(circles, rects, margin):
    """(min_x, min_y, max_x, max_y) -- every obstacle's own extent,
    grown by `margin`. Shared by build_map (the occupancy grid) and
    render_dimensioned_image (the diagram), so the two always agree on
    how much ground the map covers."""
    xs, ys = [], []
    for x, y, r, _name in circles:
        xs += [x - r - margin, x + r + margin]
        ys += [y - r - margin, y + r + margin]
    for cx, cy, yaw, length_x, length_y, _name in rects:
        half_diag = math.hypot(length_x, length_y) / 2.0
        xs += [cx - half_diag - margin, cx + half_diag + margin]
        ys += [cy - half_diag - margin, cy + half_diag + margin]
    return min(xs), min(ys), max(xs), max(ys)


def build_map(circles, rects, resolution, margin, inflate):
    """Rasterize every circle/rect obstacle into one occupancy grid,
    same shape/semantics as planning_core.py's build_grid_map: a cell is
    occupied if within `inflate` metres of any obstacle's own boundary."""
    min_x, min_y, max_x, max_y = compute_bounds(circles, rects, margin)
    width = max(1, int(math.ceil((max_x - min_x) / resolution)))
    height = max(1, int(math.ceil((max_y - min_y) / resolution)))

    data = np.zeros((height, width), dtype=np.uint8)
    rows, cols = np.indices(data.shape)
    world_x = min_x + (cols + 0.5) * resolution
    world_y = min_y + (rows + 0.5) * resolution

    for x, y, r, _name in circles:
        occ_r = r + inflate
        data[(world_x - x) ** 2 + (world_y - y) ** 2 <= occ_r ** 2] = 100

    for cx, cy, yaw, length_x, length_y, _name in rects:
        dx, dy = world_x - cx, world_y - cy
        cos_y, sin_y = math.cos(-yaw), math.sin(-yaw)
        local_x = dx * cos_y - dy * sin_y
        local_y = dx * sin_y + dy * cos_y
        half_x, half_y = length_x / 2.0 + inflate, length_y / 2.0 + inflate
        data[(np.abs(local_x) <= half_x) & (np.abs(local_y) <= half_y)] = 100

    return data, resolution, (min_x, min_y)


def write_map(data, resolution, origin, out_dir, map_name):
    """occupancy array -> <out_dir>/<map_name>.pgm + .yaml. Row 0 of
    `data` is min-y (nav_msgs/OccupancyGrid convention); a PGM's row 0
    is the TOP of the image = max-y, so flip once here, same as
    export_orchard_map.py's own write_map."""
    pixels = np.full(data.shape, PIXEL_FREE, dtype=np.uint8)
    pixels[data >= 100] = PIXEL_OCCUPIED
    pixels = np.flipud(pixels)

    os.makedirs(out_dir, exist_ok=True)
    pgm_path = os.path.join(out_dir, f"{map_name}.pgm")
    yaml_path = os.path.join(out_dir, f"{map_name}.yaml")

    Image.fromarray(pixels, mode="L").save(pgm_path)

    meta = {
        "image": f"{map_name}.pgm",
        "resolution": resolution,
        "origin": [origin[0], origin[1], 0.0],
        "negate": 0,
        "occupied_thresh": 0.65,
        "free_thresh": 0.196,
    }
    with open(yaml_path, "w") as f:
        yaml.safe_dump(meta, f, default_flow_style=False)

    return pgm_path, yaml_path


def _rect_corners(cx, cy, yaw, size_x, size_y):
    """The 4 world-frame corners of a rectangle centered at (cx, cy),
    with full side lengths (size_x, size_y) along its own LOCAL x/y
    axes before being rotated by yaw -- the inverse of the world->local
    rotation build_map's own occupancy fill uses."""
    half_x, half_y = size_x / 2.0, size_y / 2.0
    local_corners = [(-half_x, -half_y), (-half_x, half_y), (half_x, half_y), (half_x, -half_y)]
    cos_y, sin_y = math.cos(yaw), math.sin(yaw)
    return [(cx + lx * cos_y - ly * sin_y, cy + lx * sin_y + ly * cos_y)
            for lx, ly in local_corners]


def _place_label(draw, font, anchor_x, anchor_y, text, placed_boxes, color, radius_px=0.0):
    """Draws `text` near (anchor_x, anchor_y) at whichever of several
    candidate offsets doesn't overlap a label already placed (tracked in
    `placed_boxes`, mutated in place) -- a greedy declutterer, since a
    fixed "always to the right" offset is exactly what piles every
    label from a row of closely-spaced obstacles on top of each other.
    `radius_px` pushes candidates outside a circular obstacle's own
    footprint (0 for a rectangle, whose corners already frame it).
    Falls back to the first candidate (still drawn, just possibly
    overlapping) if every candidate collides -- a dense cluster can
    only be decluttered so far without hiding an obstacle entirely."""
    bbox = draw.textbbox((0, 0), text, font=font)
    w, h = bbox[2] - bbox[0], bbox[3] - bbox[1]
    pad = 2.0
    offset = radius_px + 3.0
    candidates = [
        (offset, -h / 2.0), (-offset - w, -h / 2.0),           # right, left
        (-w / 2.0, -offset - h), (-w / 2.0, offset),            # above, below
        (offset, -offset - h), (offset, offset),                # upper/lower-right
        (-offset - w, -offset - h), (-offset - w, offset),      # upper/lower-left
    ]
    chosen = None
    for dx, dy in candidates:
        x0, y0 = anchor_x + dx, anchor_y + dy
        box = (x0 - pad, y0 - pad, x0 + w + pad, y0 + h + pad)
        if not any(box[0] < b[2] and box[2] > b[0] and box[1] < b[3] and box[3] > b[1]
                   for b in placed_boxes):
            chosen = (x0, y0, box)
            break
    if chosen is None:
        dx, dy = candidates[0]
        x0, y0 = anchor_x + dx, anchor_y + dy
        chosen = (x0, y0, (x0 - pad, y0 - pad, x0 + w + pad, y0 + h + pad))
    x0, y0, box = chosen
    placed_boxes.append(box)
    draw.text((x0, y0), text, fill=color, font=font)


def _size_table(circles, rects):
    """[(label, size_text), ...] -- one row per DISTINCT obstacle type
    (trees all share one radius, fence panels all share one size), so
    the per-instance labels only need to carry id + position, not their
    size repeated ~150 times over. A house is unique per map, so it
    gets its own row too rather than being folded into "rects"."""
    rows = []
    if circles:
        radii = sorted({round(r, 3) for _, _, r, _ in circles})
        radii_text = ", ".join(f"{r:.2f}m" for r in radii)
        rows.append((f"Tree ({len(circles)}x)", f"circle, r={radii_text}"))
    fences = [r for r in rects if r[5] != "house_1"]
    if fences:
        sizes = sorted({(round(sx, 3), round(sy, 3)) for _, _, _, sx, sy, _ in fences})
        sizes_text = ", ".join(f"{sx:.2f}x{sy:.2f}m" for sx, sy in sizes)
        rows.append((f"Fence panel ({len(fences)}x)", f"rectangle, {sizes_text}"))
    houses = [r for r in rects if r[5] == "house_1"]
    for _, _, _, sx, sy, name in houses:
        rows.append((name, f"rectangle, {sx:.2f}x{sy:.2f}m"))
    return rows


def render_dimensioned_image(circles, rects, bounds, out_path, px_per_meter=15.0):
    """<out_path>.png -- a dimensioned technical diagram of the same
    layout build_map rasterizes: the world (map) reference frame's
    origin/axes, a metre grid, a size-per-obstacle-type table, and every
    obstacle drawn to scale with its own (x, y) position (relative to
    that SAME origin) labeled next to it -- positioned to avoid
    overlapping any other label already placed. For visually auditing
    the generated geometry, not something map_server ever loads."""
    min_x, min_y, max_x, max_y = bounds
    grid_step = 10.0 if max(max_x - min_x, max_y - min_y) > 60.0 else 5.0

    width_px = max(1, int(round((max_x - min_x) * px_per_meter))) + 1
    height_px = max(1, int(round((max_y - min_y) * px_per_meter))) + 1

    img = Image.new("RGB", (width_px, height_px), "white")
    draw = ImageDraw.Draw(img)
    try:
        font = ImageFont.truetype("DejaVuSans.ttf", 10)
        font_small = ImageFont.truetype("DejaVuSans.ttf", 8)
        font_table = ImageFont.truetype("DejaVuSans.ttf", 11)
    except OSError:
        font = font_small = font_table = ImageFont.load_default()

    def to_px(x, y):
        # Image row 0 is the TOP (max-y) -- same flip write_map's own
        # PGM output uses, so the diagram reads the same way up.
        return (x - min_x) * px_per_meter, height_px - (y - min_y) * px_per_meter

    def frange(lo, hi, step):
        v = math.floor(lo / step) * step
        while v <= hi + 1e-9:
            if v >= lo - 1e-9:
                yield round(v, 6)
            v += step

    # Metre grid + tick labels.
    for gx in frange(min_x, max_x, grid_step):
        px, _ = to_px(gx, min_y)
        draw.line([(px, 0), (px, height_px)], fill=(225, 225, 225))
        draw.text((px + 2, height_px - 14), f"{gx:g}", fill=(130, 130, 130), font=font_small)
    for gy in frange(min_y, max_y, grid_step):
        _, py = to_px(min_x, gy)
        draw.line([(0, py), (width_px, py)], fill=(225, 225, 225))
        draw.text((2, py - 12), f"{gy:g}", fill=(130, 130, 130), font=font_small)

    # World reference frame -- origin (0,0) and its +X/+Y axes, IF the
    # origin actually falls inside this map's own extent.
    if min_x <= 0.0 <= max_x and min_y <= 0.0 <= max_y:
        ox, oy = to_px(0.0, 0.0)
        axis_len = min(width_px, height_px) * 0.06
        draw.line([(ox, oy), (ox + axis_len, oy)], fill=(0, 0, 220), width=2)
        draw.line([(ox, oy), (ox, oy - axis_len)], fill=(0, 150, 0), width=2)
        draw.text((ox + axis_len + 3, oy - 6), "X", fill=(0, 0, 220), font=font)
        draw.text((ox - 5, oy - axis_len - 14), "Y", fill=(0, 150, 0), font=font)
        draw.ellipse([ox - 4, oy - 4, ox + 4, oy + 4], outline=(200, 0, 0), width=2)
        draw.text((ox + 6, oy + 4), "(0,0) map reference frame", fill=(200, 0, 0), font=font)

    # Every already-drawn label's own pixel bbox, so later labels can
    # dodge them -- seeded with the reference-frame label above and the
    # size table below (drawn first, once its own box is known) so
    # obstacle labels dodge those too, not just each other.
    placed_boxes = []
    if min_x <= 0.0 <= max_x and min_y <= 0.0 <= max_y:
        ox, oy = to_px(0.0, 0.0)
        placed_boxes.append((ox - 6, oy - 20, ox + 160, oy + 20))

    # Size-per-obstacle-type table, top-left corner, on its own white
    # backing so the metre grid behind it doesn't bleed through the text.
    rows = _size_table(circles, rects)
    if rows:
        row_h = 16
        col_w = max(draw.textbbox((0, 0), label, font=font_table)[2] for label, _ in rows) + 12
        table_w = col_w + max(
            draw.textbbox((0, 0), size, font=font_table)[2] for _, size in rows) + 12
        table_h = row_h * (len(rows) + 1) + 8
        draw.rectangle([4, 4, 4 + table_w, 4 + table_h], fill="white", outline=(0, 0, 0))
        draw.text((10, 8), "Obstacle sizes", fill=(0, 0, 0), font=font_table)
        for i, (label, size) in enumerate(rows):
            y = 8 + row_h * (i + 1)
            draw.text((10, y), label, fill=(0, 0, 0), font=font_table)
            draw.text((10 + col_w, y), size, fill=(0, 0, 0), font=font_table)
        placed_boxes.append((4, 4, 4 + table_w, 4 + table_h))

    # Trees -- circle to scale + "id (x,y)" label, decluttered.
    for x, y, r, name in circles:
        cx, cy = to_px(x, y)
        rp = r * px_per_meter
        draw.ellipse([cx - rp, cy - rp, cx + rp, cy + rp], outline=(230, 140, 0), width=2)
        _place_label(draw, font_small, cx, cy, f"{name} ({x:.1f},{y:.1f})",
                     placed_boxes, (150, 90, 0), radius_px=rp)

    # Fence panels / house -- rotated rectangle to scale + label, decluttered.
    for cx, cy, yaw, size_x, size_y, name in rects:
        corners = [to_px(px, py) for px, py in _rect_corners(cx, cy, yaw, size_x, size_y)]
        draw.polygon(corners, outline=(150, 0, 150))
        lx, ly = to_px(cx, cy)
        # Half the LONGER side, not the full diagonal (which over-pushes
        # a long, thin fence panel's label well past where it needs to
        # clear the shape) -- close enough to "outside the rectangle"
        # in every candidate direction _place_label tries.
        half_px = max(size_x, size_y) / 2.0 * px_per_meter
        _place_label(draw, font_small, lx, ly, f"{name} ({cx:.1f},{cy:.1f})",
                     placed_boxes, (110, 0, 110), radius_px=half_px)

    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    img.save(out_path)
    return out_path


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--world", required=True, help="Path to an orchard_map_*.sdf world file.")
    ap.add_argument("--models-dir", default=os.path.join(_PACKAGE_DIR, "models"),
                     help="Where fence/ and house_1/ live (default: this package's own models/).")
    ap.add_argument("--out", default=os.path.join(_PACKAGE_DIR, "maps"))
    ap.add_argument("--map-name", default=None, help="Defaults to the world file's own basename.")
    ap.add_argument("--resolution", type=float, default=DEFAULT_RESOLUTION,
                     help=f"Metres per cell (default: {DEFAULT_RESOLUTION}, matching "
                     "problog_project's own committed maps and this repo's own "
                     "export_orchard_map.py -- NOT the 0.05 in problog_project's "
                     "unused module/devtools/map_generation.py sample script).")
    ap.add_argument("--margin", type=float, default=DEFAULT_MARGIN,
                     help=f"Blank border beyond the outermost geometry, metres "
                     f"(default: {DEFAULT_MARGIN}, matching export_orchard_map.py).")
    ap.add_argument("--inflate", type=float, default=DEFAULT_INFLATE,
                     help=f"Occupied zone grown this far beyond each obstacle's own "
                     f"boundary, metres (default: {DEFAULT_INFLATE} = "
                     "planning_core.py's own PLANNING_INFLATE_M).")
    ap.add_argument("--dim-scale", type=float, default=15.0,
                     help="Pixels per metre in the dimensioned diagram (default: 15).")
    ap.add_argument("--no-dimensions", action="store_true",
                     help="Skip generating the <map_name>_dimensions.png diagram.")
    args = ap.parse_args()

    map_name = args.map_name or os.path.splitext(os.path.basename(args.world))[0]

    world_root = ET.parse(args.world).getroot()

    circles = parse_tree_circles(world_root)
    print(f"trees: {len(circles)}")

    fence_length, fence_thickness = get_fence_footprint(args.models_dir)
    rects = parse_fence_rects(world_root, fence_length, fence_thickness)
    print(f"fence panels: {len(rects)} ({fence_length}m x {fence_thickness}m each)")

    house_size = get_house_local_bbox(args.models_dir)
    house_rect = parse_house_rect(world_root, *house_size)
    if house_rect is not None:
        rects.append(house_rect)
        print(f"house: {house_size[0]:.2f}m x {house_size[1]:.2f}m footprint, filled solid")

    data, resolution, origin = build_map(circles, rects, args.resolution, args.margin, args.inflate)
    print(f"grid: {data.shape[1]}x{data.shape[0]} cells at {resolution} m/cell, "
          f"origin=({origin[0]:.2f}, {origin[1]:.2f})")

    pgm_path, yaml_path = write_map(data, resolution, origin, args.out, map_name)
    print(f"wrote {pgm_path}")
    print(f"wrote {yaml_path}")

    if not args.no_dimensions:
        bounds = compute_bounds(circles, rects, args.margin)
        dim_path = render_dimensioned_image(
            circles, rects, bounds,
            os.path.join(args.out, f"{map_name}_dimensions.png"),
            px_per_meter=args.dim_scale)
        print(f"wrote {dim_path}")


if __name__ == "__main__":
    main()
